sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: luozheng

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tHM4WxLsHmhLCbCBNbt
    access-key-secret: QlqNIDFGkUVQOPjEhapTSMEByjnMnm
    bucket-name: e-itcast